# Generated by Django 3.0.7 on 2020-09-19 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('bot_init', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='members_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='game.MembersGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='points',
            field=models.SmallIntegerField(default=1, verbose_name='Кол-во очков у участника'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Подписан ли польователь на бота'),
        ),
    ]
