# Generated by Django 3.0.7 on 2020-10-06 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0002_auto_20201006_1757'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='members_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='game.MembersGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='points_body',
            field=models.IntegerField(default=0, verbose_name='Уровень физ. развития'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='points_soul',
            field=models.IntegerField(default=0, verbose_name='Уровень духовного развития'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='points_spirit',
            field=models.IntegerField(default=0, verbose_name='Уровень душевного развития'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Подписан ли польователь на бота'),
        ),
    ]
