# Generated by Django 3.0.7 on 2020-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0002_auto_20200919_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='points',
            field=models.SmallIntegerField(default=0, verbose_name='Кол-во очков у участника'),
        ),
    ]
