# Generated by Django 3.0.7 on 2020-10-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0003_auto_20201006_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='step',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
