# Generated by Django 3.0.7 on 2020-09-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0003_auto_20200919_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
