# Generated by Django 3.0.7 on 2020-09-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0004_auto_20200919_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='points',
        ),
    ]
