# Generated by Django 3.0.7 on 2020-10-11 16:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0006_auto_20201011_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='registry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
