# Generated by Django 3.0.7 on 2020-10-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0007_auto_20201011_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
