# Generated by Django 3.0.7 on 2020-09-29 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0007_subscriber_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='Удалено ли сообщение у пользователя'),
        ),
    ]
