# Generated by Django 3.0.7 on 2020-10-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0008_message_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
