# Generated by Django 3.0.7 on 2020-10-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0008_message_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='step',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Шаг пользователя'),
        ),
    ]
