# Generated by Django 3.0.7 on 2020-10-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0009_subscriber_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='level',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='points_body',
            field=models.IntegerField(default=0, verbose_name='Уровень физ. развития'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='points_soul',
            field=models.IntegerField(default=0, verbose_name='Уровень духовного развития'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='points_spirit',
            field=models.IntegerField(default=0, verbose_name='Уровень душевного развития'),
        ),
    ]
