# Generated by Django 3.0.7 on 2020-10-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0009_auto_20201017_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Подписан ли польователь на бота'),
        ),
    ]
