# Generated by Django 3.0.7 on 2020-11-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0010_auto_20201031_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmessage',
            options={'verbose_name': 'Административное сообщение', 'verbose_name_plural': 'Административные сообщения'},
        ),
    ]
