# Generated by Django 3.0.7 on 2020-11-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0011_auto_20201118_2236'),
        ('bot_init', '0011_auto_20201118_1321'),
    ]

    operations = [
    ]
