# Generated by Django 3.0.7 on 2020-11-19 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0012_merge_20201118_2349'),
        ('bot_init', '0011_auto_20201117_1404'),
    ]

    operations = [
    ]
