# Generated by Django 3.0.7 on 2020-10-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201006_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddailytask',
            name='complexity',
            field=models.SmallIntegerField(default=1, verbose_name='Сложность, которую выбрал пользователь'),
            preserve_default=False,
        ),
    ]
