# Generated by Django 3.0.7 on 2020-10-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_recorddailytask_complexity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddailytask',
            name='complexity',
            field=models.SmallIntegerField(default=0, verbose_name='Сложность, которую выбрал пользователь'),
        ),
    ]
