# Generated by Django 3.0.7 on 2020-10-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20201007_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddailytask',
            name='complexity',
            field=models.IntegerField(default=0, verbose_name='Сложность, которую выбрал пользователь'),
        ),
    ]
