# Generated by Django 3.0.7 on 2020-09-26 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0007_subscriber_day'),
        ('game', '0004_auto_20200926_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordDailyTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks_records', to='bot_init.Subscriber')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks_records', to='game.DailyTask')),
            ],
        ),
    ]
