# Generated by Django 3.0.7 on 2020-10-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_init', '0006_auto_20201011_1940'),
        ('game', '0007_auto_20201008_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddailytask',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='recorddailytask',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks_records', to='game.RecordDailyTaskGroup', verbose_name='Группа подписчиков'),
        ),
        migrations.AlterField(
            model_name='recorddailytask',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='recorddailytask',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Определено в исполнение'),
        ),
        migrations.AlterField(
            model_name='recorddailytask',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks_records', to='bot_init.Subscriber', verbose_name='Подписчик'),
        ),
        migrations.AlterField(
            model_name='recorddailytask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks_records', to='game.DailyTask', verbose_name='Задача'),
        ),
    ]
