# Generated by Django 3.0.7 on 2020-09-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20200926_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recorddailytask',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks_records', to='game.RecordDailyTaskGroup'),
        ),
    ]
