# Generated by Django 3.0.7 on 2020-09-26 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20200926_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddailytask',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
