# Generated by Django 3.0.7 on 2020-11-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20201011_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images'),
        ),
    ]
