# Generated by Django 3.0.7 on 2020-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_recorddailytask_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddailytask',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
