# Generated by Django 3.0.7 on 2020-10-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_recorddailytask_is_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeginSurveyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('body', 'тело'), ('soul', 'душа'), ('spirit', 'дух')], max_length=16, verbose_name='Категория вопроса')),
                ('text', models.CharField(max_length=1000, verbose_name='Текст вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос для начального тестирования',
                'verbose_name_plural': 'Вопросы для начального тестирования',
            },
        ),
    ]
