# Generated by Django 3.0.7 on 2020-10-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20201003_1054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BeginSurveyAnswer',
            new_name='BeginSurveyQuestion',
        ),
    ]
